config/routes.rb
  Rails.application.routes.draw do

  root "welcome#index"

  get "sign-up", to: "registrations#new"
  post "sign-up", to: "registrations#create"
  get "sign-out", to: "authentication#destroy"
  get "sign-in", to: "authentication#new"
  post "sign-in", to: "authentication#create"

  resources :cheeses
end

app/models/cheese.rb
class Cheese < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password


end

app/models/welcome.rb
class Welcome < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    if session[:user_id]
      User.find(session[:user_id])
    end

  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController

  def new
    @user = User.new
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Successfully signed in"
      redirect_to cheeses_path
    else
      flash[:notice] = "User could not be authenticated. Please try again."
      render :new
    end
  end


end

app/controllers/cheeses_controller.rb
class CheesesController < ApplicationController

  def index
    if current_user
      @cheeses = Cheese.all
    else
      redirect_to '/'
      flash[:notice] = "You must register or log in before you can do that!"
    end
  end

  def new
    @cheese = Cheese.new
  end

  def create
    @cheese = Cheese.new(params.require(:cheese).permit(:name, :price_per_lb))
    if @cheese.save
      redirect_to cheeses_path
      flash[:notice] = "Cheese created successfully!"
    else
      render :edit
    end
  end

  def edit
    @cheese = Cheese.find(params[:id])
  end

  def show
    @cheese = Cheese.find(params[:id])
  end

  def update
    @cheese = Cheese.find(params[:id])
    if @cheese.update(params.require(:cheese).permit(:name, :price_per_lb))
      redirect_to cheese_path
      flash[:notice] = "Cheese updated successfully!"
    else
      render :edit
    end
  end

  def destroy
    @cheese = Cheese.find(params[:id])
      flash[:notice] = "Deleted cheese: " + @cheese.name
        @cheese.destroy
      redirect_to cheeses_path
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:email, :password))
      if @user.save
        session[:user_id] = @user.id
          flash[:notice] = "Successfully signed up"
        redirect_to cheeses_path
      else
        render :new
      end
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @user = User.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authentication/new.html.haml
Sign In Form
= form_tag sign_in_path do |f|

  = label_tag :email
  = text_field_tag :email

  = label_tag :password
  = password_field_tag :password

  = submit_tag "Sign in"

app/views/cheeses/edit.html.haml
= form_for @cheese do |f|

  = f.label :name
  = f.text_field :name

  = f.label :price_per_lb
  = f.text_field :price_per_lb

  = f.submit "Update Cheese"

app/views/cheeses/index.html.haml
- if current_user
  = link_to "Sign out", sign_out_path
  %h2 List of Cheeses
- else
  = link_to "Sign me in Nobody is logged in", sign_in_path
  = link_to "Sign up", sign_up_path
  = link_to "Sign in", sign_in_path


- if current_user
  - @cheeses.each do |cheese|
    = link_to "#{cheese.name} - $#{cheese.price_per_lb}", cheese_path(cheese)
    = link_to "Edit Cheese", edit_cheese_path(cheese)
- else
  Welcome, please click the sign up or sign in links below


= link_to "New Cheese", new_cheese_path

app/views/cheeses/new.html.haml
= form_for @cheese, url: cheeses_path do |f|

  = f.label :name
  = f.text_field :name

  = f.label :price_per_lb
  = f.text_field :price_per_lb

  = f.submit "Create Cheese"

app/views/cheeses/show.html.erb
Cheese Name:
<%=@cheese.name %>
<br>
Cheese Price ($/lb): $<%=@cheese.price_per_lb %>

<%= link_to "Edit", edit_cheese_path %>
<%= link_to "Index", cheeses_path %>
<%= link_to "Destroy", cheese_path(@cheese), method: :delete, data: {confirm: "Are you sure you want to delete"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BamUserAuth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= flash[:notice] %>
<%= yield %>

</body>
</html>

app/views/welcome/index.html.haml
Welcome, please click the sign up or sign in links below

= link_to "Sign in", sign_in_path
  
= link_to "Sign up", sign_up_path